# This is a basic workflow to help you get started with Actions

name: CI devops 2022 EPF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build-and-test-app:
  # This workflow contains a single job called "build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3

      #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
        
      # Finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file /single-api/pom.xml
